project:
  type: website

website:
  title: Zero to Website with Quarto
  description: "Zero to website with Quarto Workshop for Cascadia R Conf 2026"
  site-url: https://cwickham.github.io/cascadia2026
  image: thumbnail.jpeg
  image-alt: "Zero to Website with Quarto with a screenshot of a website titled 'Alicia, Data Scientist'."
  open-graph: true 
  search: false
  page-footer: "Made with ❤️ and Quarto"
  sidebar:
    title: Zero to Website with Quarto Workshop 
    alignment: center
    style: floating
    logo: image.png
    logo-alt: Cascadia R Conf 2026 hex sticker
    contents:
      - href: index.qmd
        text: Home
      - prework.qmd
      - materials.qmd
    tools:
      - icon: github
        aria-label: Github repo
        href: https://github.com/cwickham/cascadia2026

format:
  html:
    syntax-highlighting: a11y